### ISSUE TITLE
タグ　閉じてない

### ISSUE THREAD

**Issue by kadoshita** [inct-hatsumei/inct-hatsumei.github.io#2]
https://github.com/inct-hatsumei/inct-hatsumei.github.io/blob/73e42e61405ba5c8650011fc75dbc63bed618258/index.html#L129

aタグが閉じてない

**Comment by Yukibara** [comment]
対応しました

**Comment by kadoshita** [comment]
@Brrnt 直ってなかった
`<a href="mailto:inct.hatsumei@gmail.com">inct.hatsumei@gmail.com</a>`
こうだね
VS Code使うといいよ

**Comment by Yukibara** [comment]
@Kadoshita ありがとうございます、多分直りました！
